# Generated by Django 2.1.1 on 2018-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('DESKTOP', 'DESKTOP'), ('LAPTOP', 'Laptop'), ('ACCESSORIES', 'Accessories'), ('HARDWARE', 'Hardware'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
            ],
        ),
    ]
