# Generated by Django 2.1.1 on 2018-09-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlogin',
            name='vpassword',
            field=models.CharField(default='root1234', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendorlogin',
            name='vname',
            field=models.CharField(max_length=50),
        ),
    ]
