# Generated by Django 2.1.1 on 2018-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20180916_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlogin',
            name='vname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorlogin',
            name='vpassword',
            field=models.CharField(default='', max_length=30),
        ),
    ]
