# Generated by Django 2.1.1 on 2018-09-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20180916_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorlogin',
            old_name='vpassword',
            new_name='vendor_password',
        ),
        migrations.RenameField(
            model_name='vendorlogin',
            old_name='vname',
            new_name='vendor_username',
        ),
    ]
