# Generated by Django 2.1.1 on 2018-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=255)),
                ('proprice', models.DecimalField(decimal_places=5, max_digits=10)),
                ('prodesc', models.TextField()),
                ('proimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
