# Generated by Django 2.1.1 on 2018-09-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodesc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='proimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='proprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='proname',
            new_name='title',
        ),
    ]
