# Generated by Django 2.1.1 on 2018-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180903_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DT', 'DESKTOP'), ('LT', 'Laptop'), ('AC', 'Accessories'), ('HW', 'Hardware'), ('UN', 'Unknown')], default='UN', max_length=10),
        ),
    ]
